# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tally < Formula
  desc "The AI principal engineer for every developer — quality gate for AI-generated code"
  homepage "https://tally.sh"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suannai231/tally-releases/releases/download/v0.4.0/tally_0.4.0_darwin_amd64.tar.gz"
      sha256 "fa1e78251d16a38a35f0d52189a5cb0685bc391a80358daf177fedab35400350"

      define_method(:install) do
        bin.install "tally"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suannai231/tally-releases/releases/download/v0.4.0/tally_0.4.0_darwin_arm64.tar.gz"
      sha256 "ef681182e26ca2bff8dc1ed01fde589f222af746eebfdd3f51e24a3960c0f5c5"

      define_method(:install) do
        bin.install "tally"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/suannai231/tally-releases/releases/download/v0.4.0/tally_0.4.0_linux_amd64.tar.gz"
      sha256 "e431b689ee5d26eca86372e4d9d726804ca077b9bfae2aba7b38eca64b128fe9"
      define_method(:install) do
        bin.install "tally"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suannai231/tally-releases/releases/download/v0.4.0/tally_0.4.0_linux_arm64.tar.gz"
      sha256 "3d531371eed9b9114869e1c8c720951f467591429fa2f3c4a2cd9c4ceeed938e"
      define_method(:install) do
        bin.install "tally"
      end
    end
  end

  test do
    system "#{bin}/tally", "--version"
  end
end
